create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  "fullName" text not null default '',
  email text not null unique,
  role text not null default 'buyer' check (role in ('buyer', 'admin')),
  phone text not null default '',
  company text not null default '',
  address text not null default '',
  city text not null default '',
  state text not null default '',
  "postalCode" text not null default '',
  country text not null default '',
  "cardName" text not null default '',
  "cardNumber" text not null default '',
  "cardExpiry" text not null default '',
  "cardCvv" text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.items (
  auction_id bigint generated by default as identity unique,
  slug text primary key,
  title text not null,
  category text not null,
  summary text not null,
  mode text not null check (mode in ('auction', 'buy-now', 'hybrid')),
  status text not null default 'draft' check (status in ('draft', 'scheduled', 'live', 'closed', 'sold', 'archived')),
  location text not null,
  shipping text not null,
  "currentBid" numeric,
  "buyNowPrice" numeric,
  minimum_bid numeric,
  reserve_price numeric,
  starts_at timestamptz,
  ends_at timestamptz,
  "endsIn" text,
  stock integer not null default 1,
  grade text not null,
  gradient text not null,
  highlights jsonb not null default '[]'::jsonb,
  "seoDescription" text not null,
  currency_code text not null default 'USD',
  "bidIncrement" numeric,
  "bidCount" integer,
  watchers integer,
  "reserveMet" boolean,
  seller text,
  "lotNumber" text,
  created_by_email text,
  updated_by_email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists role text not null default 'buyer';

alter table public.items
  add column if not exists auction_id bigint generated by default as identity;

alter table public.items
  add column if not exists status text not null default 'draft';

alter table public.items
  add column if not exists minimum_bid numeric;

alter table public.items
  add column if not exists reserve_price numeric;

alter table public.items
  add column if not exists starts_at timestamptz;

alter table public.items
  add column if not exists ends_at timestamptz;

alter table public.items
  add column if not exists currency_code text not null default 'USD';

alter table public.items
  add column if not exists created_by_email text;

alter table public.items
  add column if not exists updated_by_email text;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_role_check'
  ) then
    alter table public.profiles
      add constraint profiles_role_check check (role in ('buyer', 'admin'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'items_status_check'
  ) then
    alter table public.items
      add constraint items_status_check
      check (status in ('draft', 'scheduled', 'live', 'closed', 'sold', 'archived'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'items_auction_id_key'
  ) then
    alter table public.items add constraint items_auction_id_key unique (auction_id);
  end if;
end $$;

create table if not exists public.bids (
  id uuid primary key default gen_random_uuid(),
  item_slug text not null references public.items (slug) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  amount numeric not null,
  max_amount numeric,
  status text not null default 'active' check (status in ('active', 'winning', 'outbid', 'cancelled')),
  created_at timestamptz not null default now()
);

create table if not exists public.item_assets (
  id uuid primary key default gen_random_uuid(),
  item_slug text not null references public.items (slug) on delete cascade,
  asset_url text not null,
  alt_text text not null default '',
  sort_order integer not null default 0,
  is_primary boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete restrict,
  status text not null default 'pending' check (status in ('pending', 'authorized', 'paid', 'failed', 'fulfilled', 'cancelled', 'refunded')),
  order_type text not null default 'auction-win' check (order_type in ('auction-win', 'buy-now', 'manual')),
  subtotal numeric not null default 0,
  currency_code text not null default 'USD',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders (id) on delete cascade,
  item_slug text not null references public.items (slug) on delete restrict,
  quantity integer not null default 1,
  unit_price numeric not null,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor_email text,
  actor_user_id uuid references public.profiles (id) on delete set null,
  entity_type text not null,
  entity_id text not null,
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.bids
  add column if not exists max_amount numeric;

alter table public.bids
  add column if not exists status text not null default 'active';

create index if not exists bids_item_slug_created_at_idx on public.bids (item_slug, created_at desc);
create index if not exists bids_user_id_created_at_idx on public.bids (user_id, created_at desc);
create index if not exists item_assets_item_slug_sort_order_idx on public.item_assets (item_slug, sort_order asc);
create index if not exists orders_user_id_created_at_idx on public.orders (user_id, created_at desc);
create index if not exists audit_logs_entity_idx on public.audit_logs (entity_type, entity_id, created_at desc);
create index if not exists items_mode_idx on public.items (mode);
create index if not exists items_category_idx on public.items (category);
create index if not exists items_status_idx on public.items (status);
create index if not exists items_starts_at_idx on public.items (starts_at);
create index if not exists items_ends_at_idx on public.items (ends_at);

alter table public.profiles enable row level security;
alter table public.items enable row level security;
alter table public.bids enable row level security;
alter table public.item_assets enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.audit_logs enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'items' and policyname = 'Public read items'
  ) then
    create policy "Public read items" on public.items for select using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'profiles' and policyname = 'Users read own profile'
  ) then
    create policy "Users read own profile" on public.profiles
      for select using (auth.uid() = id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'profiles' and policyname = 'Users update own profile'
  ) then
    create policy "Users update own profile" on public.profiles
      for update using (auth.uid() = id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'profiles' and policyname = 'Admins read profiles'
  ) then
    create policy "Admins read profiles" on public.profiles
      for select using (
        exists (
          select 1
          from public.profiles admin_profile
          where admin_profile.id = auth.uid() and admin_profile.role = 'admin'
        )
      );
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'bids' and policyname = 'Users read bids'
  ) then
    create policy "Users read bids" on public.bids for select using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'bids' and policyname = 'Users insert own bids'
  ) then
    create policy "Users insert own bids" on public.bids
      for insert with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'item_assets' and policyname = 'Public read item assets'
  ) then
    create policy "Public read item assets" on public.item_assets for select using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'orders' and policyname = 'Users read own orders'
  ) then
    create policy "Users read own orders" on public.orders
      for select using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'order_items' and policyname = 'Users read own order items'
  ) then
    create policy "Users read own order items" on public.order_items
      for select using (
        exists (
          select 1
          from public.orders o
          where o.id = order_id and o.user_id = auth.uid()
        )
      );
  end if;
end $$;
