insert into public.items (
  slug, title, category, summary, mode, location, shipping, "currentBid", "buyNowPrice",
  "endsIn", stock, grade, gradient, highlights, "seoDescription", "bidIncrement", "bidCount",
  watchers, "reserveMet", seller, "lotNumber"
)
values
  (
    'dewalt-contractor-tool-bundle',
    'DeWalt Contractor Tool Bundle',
    'Tools & DIY',
    'A mixed contractor lot with cordless drills, impact drivers, batteries, and chargers packed for fast resale.',
    'hybrid',
    'Dallas, USA',
    'Pallet freight across the lower 48',
    2400,
    3190,
    '5h 10m',
    1,
    'Returns A/B mix',
    'linear-gradient(135deg, #ffe1a8 0%, #f2c55f 100%)',
    '["96 units","Manifest included","Estimated margin 34%"]'::jsonb,
    'Bid or buy a DeWalt tool bundle with manifest-backed stock, clear condition notes, and pallet freight delivery.',
    50,
    18,
    46,
    true,
    'Prime Surplus Supply',
    'TL-2048'
  ),
  (
    'kitchen-appliance-clearance-pallet',
    'Kitchen Appliance Clearance Pallet',
    'Home & Kitchen',
    'Air fryers, blenders, kettles, coffee machines, and countertop appliances from big-box retail overstock.',
    'auction',
    'New Jersey, USA',
    'Warehouse pickup or arranged freight',
    1850,
    null,
    '14h 45m',
    1,
    'Overstock',
    'linear-gradient(135deg, #f8e7c8 0%, #fff4de 100%)',
    '["72 units","Retail-ready packaging","High-turn inventory"]'::jsonb,
    'Auction a kitchen appliance pallet featuring overstock small appliances with warehouse pickup and freight support.',
    25,
    11,
    29,
    false,
    'Metro Retail Recovery',
    'HK-1182'
  ),
  (
    'gaming-accessories-carton-lot',
    'Gaming Accessories Carton Lot',
    'Electronics',
    'Controllers, headsets, charging docks, RGB keyboards, and streaming gear ideal for online marketplaces.',
    'buy-now',
    'Los Angeles, USA',
    'Tracked ground shipping',
    null,
    1295,
    null,
    18,
    'Shelf-pull',
    'linear-gradient(135deg, #dbe6ff 0%, #edf2ff 100%)',
    '["58 units","Serialized SKUs","Fast dispatch"]'::jsonb,
    'Buy a gaming accessories carton lot with fast dispatch, clean packaging, and strong marketplace demand.',
    null,
    null,
    14,
    null,
    'West Coast Tech Lots',
    'EL-3301'
  ),
  (
    'designer-apparel-mixed-rack',
    'Designer Apparel Mixed Rack',
    'Clothing',
    'A curated fashion lot of outerwear, denim, knitwear, and basics sourced from seasonal retailer clear-outs.',
    'hybrid',
    'Miami, USA',
    'Freight or local pickup',
    3100,
    4125,
    '1d 3h',
    1,
    'Department store returns',
    'linear-gradient(135deg, #ead6d3 0%, #f7ece9 100%)',
    '["210 garments","Assorted sizes","Boutique-ready assortment"]'::jsonb,
    'Shop a designer apparel mixed rack with curated styles, assorted sizes, and flexible freight pickup.',
    100,
    24,
    67,
    true,
    'Southline Apparel Auctions',
    'FA-9077'
  ),
  (
    'office-furniture-liquidation-set',
    'Office Furniture Liquidation Set',
    'Office',
    'Task chairs, desks, filing cabinets, and monitor arms recovered from a modern office refit project.',
    'auction',
    'Chicago, USA',
    'Local pickup only',
    4200,
    null,
    '2d 6h',
    1,
    'Used - very good',
    'linear-gradient(135deg, #dedede 0%, #f6f6f6 100%)',
    '["48 pieces","Commercial grade","Ideal for startups"]'::jsonb,
    'Auction an office furniture liquidation set with premium commercial pieces and organized local pickup.',
    100,
    9,
    18,
    false,
    'Loop Workspace Liquidators',
    'OF-4410'
  ),
  (
    'beauty-and-skincare-bundle',
    'Beauty and Skincare Bundle',
    'Beauty',
    'Face serums, moisturizers, masks, and gift sets from excess seasonal inventory packed in shelf-ready cartons.',
    'buy-now',
    'Phoenix, USA',
    'Parcel and LTL options',
    null,
    980,
    null,
    32,
    'New and sealed',
    'linear-gradient(135deg, #f7dce7 0%, #fff1f5 100%)',
    '["120 pieces","Current expiry windows","Beauty-store friendly"]'::jsonb,
    'Buy a beauty and skincare bundle with sealed inventory, current expiry windows, and quick parcel delivery.',
    null,
    null,
    21,
    null,
    'Glow Wholesale Outlet',
    'BT-5520'
  )
on conflict (slug) do update
set
  title = excluded.title,
  category = excluded.category,
  summary = excluded.summary,
  mode = excluded.mode,
  location = excluded.location,
  shipping = excluded.shipping,
  "currentBid" = excluded."currentBid",
  "buyNowPrice" = excluded."buyNowPrice",
  "endsIn" = excluded."endsIn",
  stock = excluded.stock,
  grade = excluded.grade,
  gradient = excluded.gradient,
  highlights = excluded.highlights,
  "seoDescription" = excluded."seoDescription",
  "bidIncrement" = excluded."bidIncrement",
  "bidCount" = excluded."bidCount",
  watchers = excluded.watchers,
  "reserveMet" = excluded."reserveMet",
  seller = excluded.seller,
  "lotNumber" = excluded."lotNumber",
  updated_at = now();
