create extension if not exists pgcrypto;

alter table if exists public.profiles
  add column if not exists role text not null default 'buyer';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_role_check'
  ) then
    alter table public.profiles
      add constraint profiles_role_check check (role in ('buyer', 'admin'));
  end if;
end $$;

alter table if exists public.items
  add column if not exists auction_id bigint generated by default as identity;
alter table if exists public.items
  add column if not exists status text not null default 'draft';
alter table if exists public.items
  add column if not exists minimum_bid numeric;
alter table if exists public.items
  add column if not exists reserve_price numeric;
alter table if exists public.items
  add column if not exists starts_at timestamptz;
alter table if exists public.items
  add column if not exists ends_at timestamptz;
alter table if exists public.items
  add column if not exists currency_code text not null default 'USD';
alter table if exists public.items
  add column if not exists created_by_email text;
alter table if exists public.items
  add column if not exists updated_by_email text;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'items_status_check'
  ) then
    alter table public.items
      add constraint items_status_check
      check (status in ('draft', 'scheduled', 'live', 'closed', 'sold', 'archived'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'items_auction_id_key'
  ) then
    alter table public.items
      add constraint items_auction_id_key unique (auction_id);
  end if;
end $$;

alter table if exists public.bids
  add column if not exists max_amount numeric;
alter table if exists public.bids
  add column if not exists status text not null default 'active';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'bids_status_check'
  ) then
    alter table public.bids
      add constraint bids_status_check check (status in ('active', 'winning', 'outbid', 'cancelled'));
  end if;
end $$;

create table if not exists public.item_assets (
  id uuid primary key default gen_random_uuid(),
  item_slug text not null references public.items (slug) on delete cascade,
  asset_url text not null,
  alt_text text not null default '',
  sort_order integer not null default 0,
  is_primary boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete restrict,
  status text not null default 'pending' check (status in ('pending', 'authorized', 'paid', 'failed', 'fulfilled', 'cancelled', 'refunded')),
  order_type text not null default 'auction-win' check (order_type in ('auction-win', 'buy-now', 'manual')),
  payment_method text not null default 'cod' check (payment_method in ('cod', 'whish')),
  payment_status text not null default 'pending' check (payment_status in ('pending', 'awaiting_payment', 'paid', 'failed', 'awaiting_cod_confirmation', 'collected', 'cancelled')),
  shipping_address jsonb not null default '{}'::jsonb,
  notes text,
  subtotal numeric not null default 0,
  currency_code text not null default 'USD',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders (id) on delete cascade,
  item_slug text not null references public.items (slug) on delete restrict,
  quantity integer not null default 1,
  unit_price numeric not null,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor_email text,
  actor_user_id uuid references public.profiles (id) on delete set null,
  entity_type text not null,
  entity_id text not null,
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.payment_attempts (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders (id) on delete cascade,
  provider text not null check (provider in ('whish', 'cod')),
  provider_reference text,
  provider_status text not null default 'created',
  payment_url text,
  request_payload jsonb not null default '{}'::jsonb,
  response_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists item_assets_item_slug_sort_order_idx on public.item_assets (item_slug, sort_order asc);
create index if not exists orders_user_id_created_at_idx on public.orders (user_id, created_at desc);
create index if not exists audit_logs_entity_idx on public.audit_logs (entity_type, entity_id, created_at desc);
create index if not exists payment_attempts_order_id_created_at_idx on public.payment_attempts (order_id, created_at desc);
create index if not exists items_status_idx on public.items (status);
create index if not exists items_starts_at_idx on public.items (starts_at);
create index if not exists items_ends_at_idx on public.items (ends_at);
